# Generated by Django 4.0.2 on 2022-02-19 00:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_autor_post_alter_post_data_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo_post',
            field=ckeditor.fields.RichTextField(verbose_name='Conteudo'),
        ),
    ]
